#!/usr/bin/env bash
sudo pacman -Syu

if ! command -v git &> /dev/null; then
  sudo pacman -S --noconfirm git
fi

if [ ! -d $HOME/personal ]; then
  mkdir $HOME/personal
fi

# install yay
sudo pacman -S --needed --noconfirm base-devel

if [ ! -d $HOME/src ]; then
  mkdir $HOME/src
fi

cd $HOME/src
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si

git clone -b https://github.com/robzolkos/dev $HOME/personal/dev

cd $HOME

pushd $HOME/personal/dev
./run
popd
